---
- name: install dependencies
  apt:
    name: 
      - net-tools
      - dphys-swapfile
      - unattended-upgrades
      - apt-transport-https
      - ca-certificates
      - gnupg2
      - software-properties-common
    update_cache: yes
    state: latest

- name: set swappiness to 10 when less than 10% memory left
  sysctl:
    name: vm.swappiness
    value: '10'
    state: present
    reload: yes
  when: not CI_TEST

- name: set/increase cache pressure to 50
  sysctl:
    name: vm.vfs_cache_pressure
    value: '50'
    state: present
    reload: yes
  when: not CI_TEST

- name: add 3cx signing key
  apt_key:
    url: http://downloads-global.3cx.com/downloads/3cxpbx/public.key
    state: present

- name: add 3cx repo
  apt_repository:
    repo: deb http://downloads-global.3cx.com/downloads/debian {{ ansible_distribution_release }} main
    state: present

- name: install 3cx
  apt:
    name: 3cxpbx
    update_cache: yes
    state: latest
  notify: start 3cx
